### ISSUE TITLE
New message pill is a zombie... you tap it, it goes away, and it comes back after a minute or two

### ISSUE THREAD

**Issue by boreq** [planetary-social/planetary-ios#1175]
>One thing i'm noticing with 402... is it keeps repeating the '26 new messages' pill

We recently fixed the new messages pill in https://github.com/planetary-social/planetary-ios/pull/1086 but apparently now it works too well and permanently shows up at the top of the screen.

![Screenshot 2023-02-21 at 8 19 12 AM](https://user-images.githubusercontent.com/1935975/220184881-b693d87b-6450-426e-a382-2f5d27dc7108.png)

**Comment by martindsq** [comment]
I cannot say for sure that this is the cause, but I found that the algorithm to fetch the messages to show only fetches follows whereas the algorithm that count the number of messages since the one at the top fetches follows and unfollows. So, if someone unfollowed 26 people after the last one you have, it will shiow 26 but no messages will be displayed.

Is this behavior of the new message pill consistent, or it is something you saw once?

**Comment by martindsq** [comment]
Test again after fixing #1218

**Comment by boreq** [comment]
Is this still blocked? We fixed https://github.com/planetary-social/planetary-ios/issues/1218.
