### ISSUE TITLE
Work on improved responsiveness on follow button.

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#252]
Sometimes when tapping the follow button it looks like it's doing something but then reverts back to saying "Follow" without an error message.

**Comment by mplorentz** [comment]
I found at least one cause of this issue today, and I think it could be causing other issues throughout the app. 

The `ViewDatabase` can get significantly behind the GoSSB/Margaret database. By default it looks like the `MissionControlCenter` is fetching 500 messages from GoSSB every 60 seconds. This seems like a design decision to avoid the app being extremely slow during initial replication. IMO this is too low, as the app is only spending about 1 second getting new data every 60 seconds. My test identity quickly got 40000 messages behind the Go log. There are several situations where we do fetch more than 500 messages from the Go log, notably most pull-to-refresh gestures, but we should still probably be fetching more by default. But this in itself isn't a problem per-se.

The problem is that messages that the user publishes are only written to the `ViewDatabase` with the same priority as everyone else's messages. So if your `ViewDatabase` is out of date with the Go log and you publish a follow message to the Go log the UI won't reflect the follow until the `ViewDatabase` catches up.

I think the best way to fix this is to write any messages that the user publishes into the `ViewDatabase` immediately after they are written to the GoSSB log. It doesn't look like we have functions in `GoSSB.h` to do this specifically but I don't think it will be too hard to add.

**Comment by mplorentz** [comment]
I opened a new ticket for the View Database getting behind go-ssb: #284
