### ISSUE TITLE
Confirm that apple deep linking to planetary.link works

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#329]

**Comment by mplorentz** [comment]
This still isn't working on my device. I'm taking another look this morning.

**Comment by rabble** [comment]
Just checked as of Feb 9th and it's not working.

**Comment by setch-l** [comment]
@mplorentz or @nichoth - How would I test this to verify it is working?

**Comment by mplorentz** [comment]
@setch-l If you tap any planetary.link URL on iOS (in a place that supports link detection, like the Notes app) it should open Planetary. If you have the message downloaded already it should show it. Otherwise it will show an error message (https://github.com/planetary-social/planetary-ios/issues/380). Here is one you can use to test: https://planetary.link/%25V5m1QkfEdHx7HlJxo9gDmpsbvQPXRMlUwyLi4jpM7LQ%3D.sha256

**Comment by mplorentz** [comment]
Actually I just tested this myself and it looks like the planetary.link URLs have changed since I implemented this ticket. There is now a `/msg/` path between the host name and message ID. @nichoth is this a permanent change? If so I'll need to update the iOS app to use the new format, and this will break existing planetary.link URLs. I'm curious if there will be other paths for author and/or blob links too.

**Comment by nichoth** [comment]
hmm ok. I have to check if we can do this a different way in the web viewer

**Comment by nichoth** [comment]
I was able to add the route `/msgId`, so it should be ok now. its in https://github.com/planetary-social/viewer-frontend/pull/109

**Comment by mplorentz** [comment]
@nichoth cool, thanks! The links generated by Planetary iOS are correctly opening on planetary.link now. 

It looks like planetary.link is still using the `/msg/msgId` URLs. For instance, if I "copy link to message" on planetary.link and open that on iOS it won't open in the app. Is that the URL format you want to stick with long-term? If so, I should probably add support for that route on iOS.

**Comment by nichoth** [comment]
I noticed there was an odd bug where some URLs would work and some would fail, depending on what characters were inside it. I think I fixed it though. 

URLs are a little bit odd because the `planetary.link` site uses `/id`, and the our pub server is using `/msg/id`, but users should never see the pub URLs in practice.
