### ISSUE TITLE
Tap target to edit bio is too small on iPad

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#460]
When editing your bio on the iPad, the tap target to get the keyboard to present is way to small. This has led multiple users to think that it is broken and they can't edit their bio at all. We should expand it to fill all the whitespace.

![IMG_940D5DB8B06D-1](https://user-images.githubusercontent.com/1165004/160631981-befd382a-4dd1-4b22-ac2e-3a8c661024e6.jpeg)

**Comment by czuria1** [comment]
@mplorentz mind if I take a crack at fixing this one?

**Comment by mplorentz** [comment]
@czuria1 all yours! Please reach out here or on Matrix or Discord if you have any issues.

**Comment by czuria1** [comment]
I notice that this view is shared between iPhone and iPad, so this bug is on both. If the goal is to have the tap area be the entire bottom empty area, then should the text view be below the "Bio" label? Or any thoughts or direction how the tap area and label placements should be?
| | |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/36312970/193976343-ffae844e-c5f1-4de9-93d8-6950b158204d.png)  | ![image](https://user-images.githubusercontent.com/36312970/193976831-a927b1e2-4088-4fcc-aa72-5123da3f1f88.png)  |

**Comment by Chardot** [comment]
@czuria1 @mplorentz I also think the text area for the bio should occupy the entire bottom area. Additionally, it would be great if both fields were 100%-width block elements that sit right below their labels as shown in the picture:
![EditProfile](https://user-images.githubusercontent.com/477835/194481837-dce8a337-a422-436f-9e5d-d7cba7cb4906.png)

To make the interactive area more noticeable, their border could be the same style (width and color) as the current separator line between them, for both light and dark modes.

**Comment by czuria1** [comment]
Thank you for the input and feedback @mplorentz @Chardot! I agree on the gray border and be consistent on the styling for both 🙂 I'll work on updating that component!

**Comment by mplorentz** [comment]
This is complete! Thanks for the contribution @czuria1!
