### ISSUE TITLE
Excessive pub messages

### ISSUE THREAD

**Issue by clehner** [planetary-social/planetary-ios#509]
Repeated `pub`-type messages. Only one pub message per {author, pub, address} should be necessary generally. But we are seeing duplicate ones and large amounts (1000+) in some feeds.

Observed in feed id `@pODRaoyrPvYuwMWNOG+FkgKizJVUe4rAPVFMCsajxfg=.ed25519` and `@4GgMqiQL2gPkGO7dtx4PFTgAE2oFQB4gKyvULtTmNuY=.ed25519` in particular, and also in others.

Screenshot of some of these in patchfoo: [%eBxJPzgXuMOrDqyppQiJ/6sbHx5Jh6n1jERkXMRM5SA=.sha256](https://viewer.scuttlebot.io/%25eBxJPzgXuMOrDqyppQiJ%2F6sbHx5Jh6n1jERkXMRM5SA%3D.sha256)
![2022-04-20-planetary-connections-patchfoo.png](https://viewer.scuttlebot.io/&w3TjkNm/40MaaNZdAWwm5fZiSirijVmKQBlqJxjhFp4=.sha256)

and more:
![2022-04-20-115859_670x659_scrot](https://user-images.githubusercontent.com/95347/164273195-213d5d2a-b53f-43e4-9f0d-fb0113d78837.png)

**Comment by mplorentz** [comment]
Thanks for filing this @clehner. This was a bad one. It went out into production in release [1.1.0](https://github.com/planetary-social/planetary-ios/releases/tag/1.1.0) on April 5th and was fixed in #495 which was released to production in 1.1.1 this past Monday, April 18th. Approximately 88% of our users have updated to 1.1.1 already so you should see very few, if any, more of these being published.

**Comment by clehner** [comment]
OK, thanks @mplorentz. I think this issue can be closed then since it's fixed in the release.
