### ISSUE TITLE
small ios devices layout problems

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-ios#700]
![Screen Shot 2022-07-08 at 4 43 46 PM](https://user-images.githubusercontent.com/76/177918611-a6cf0fac-b204-4c42-9824-ca492287ac4d.png)

On smaller iOS devices you can't press the 'Phew! I'm done!" button because the options text area is overlaid. There are a number of other things which don't work with smaller screens. This is just a matter of going through the screens and changing the layering order for the layout.

**Comment by mplorentz** [comment]
Hi @Max-Rai, thanks for helping out! I went ahead and assigned the issue to you. If you haven't seen it already our [contributing docs](https://github.com/planetary-social/planetary-ios/blob/main/CONTRIBUTING.md) might be helpful to you. If you have questions while working feel free to ask them here or in our Matrix room or Discord server.

**Comment by Max-Rai** [comment]
Hi @mplorentz created this PR https://github.com/planetary-social/planetary-ios/pull/703 to fix attached screen's action layering. Let me know in case of any issues, I will fix.
Would suggest to make the base as scrollview, since the text behind the action still won't be visible, unless allowed to scroll in small screens. 

![Simulator Screen Shot - iPod touch (7th generation) - 2022-07-08 at 23 37 13](https://user-images.githubusercontent.com/1836068/178048332-9c731fc1-39f3-4d50-bf50-70ba60e54bdf.png)

**Comment by mplorentz** [comment]
@Max-Rai thanks for the fix! I think embedding these views inside scroll views would be a good next step. If you are interested in giving that a try that would be great! Otherwise I'll leave this ticket open so we can get back to it at some point.
