### ISSUE TITLE
Talk to trav about booth

### ISSUE THREAD

**Issue by mplorentz** [planetary-social/planetary-ios#757]

**Comment by mplorentz** [comment]
CC @mixmix

**Comment by mixmix** [comment]
sent him a DM on ssb.

@rabble would be good to know what resources Planetary would be prepared to offer.
SSBC is down to offer $200USD I think to help cover hardware.

If you'd like to contribute to funding the time to build stuff, would be cool to consider what that looks like. e.g. $500, $1000

**Comment by mixmix** [comment]
Rabble connected with him

**Comment by mixmix** [comment]
This isn't resolved - I've asked Trav to open a request for funds on open collective for the 200 i committed.

I don't mind if you don't want to contribute funds @rabble , but I do expect you to be clear about it.

I suggested this as an example of an artist who was contributing to the space because you had said planetary was considering finding artists. If this wasn't quite what you meant, or you weren't ready for it that's ok. Let's just practice resolving miscommunication/ misalignments. This builds trust and alignment

♥ 🍍 🐦

**Comment by boreq** [comment]
Ooops, I closed this because we were trying to clean up the tickets and the conclusion was "Rabble talked with trav" and the last comment was "Rabble connected with him". I think it was unclear what was supposed to happen here.

@rabble I am moving this to "TODO".

**Comment by mixmix** [comment]
No offense taken, you're right the initiatial task was "done". I expected a
quick yes/no after connect

**Comment by boreq** [comment]
@rabble talked with Trav as fas as I know.
