### ISSUE TITLE
Cannot delete reply to post

### ISSUE THREAD

**Issue by lincolnanders5** [planetary-social/planetary-ios#77]
I left a reply to a post, and went to first edit it (not present) then to delete in order to repost an edited version. Deleting prompted the dialog "Sorry, there was an error when trying to delete your post." Tried this three times on and off of Wi-Fi.

**Comment by rabble** [comment]
So the app is offline first, so with the exception of the directory it should make no difference if you've got an internet connection or not. Any changes you make will propagate the next time you connect.

In terms delete, it's a work in progress. In order to really support delete in scuttlebutt we need to use the new [GabbyGrove feed format](https://github.com/ssbc/ssb-spec-drafts/blob/master/drafts/draft-ssb-core-gabbygrove/00/draft-ssb-core-gabbygrove-00.md). It works with the Planetary app but doesn't work with most of the rest of the scuttlebutt implementations. 

We do need to update the UI to show that at the moment real delete isn't possible. We are working on adding a message to tell clients to hide posts from their peers they don't want to show.

If you're a node/js developer, we'd love help getting GabbyGrove support in the [ssbc repos](https://github.com/ssbc/).

**Comment by lincolnanders5** [comment]
I should’ve been more specific, but I was switching between WiFi and cellular data.

Coincidentally, I am a Node developer, so I’ll check out that when the term is over!

**Comment by mplorentz** [comment]
Closing this, since we no longer show a delete button in the app. It is still something on the roadmap though.
