### ISSUE TITLE
Onboarding process stuck at display name entry

### ISSUE THREAD

**Issue by quickdudley** [planetary-social/planetary-ios#844]
I am trying to set up Planetary on my phone again (see: #340) but cannot get through the onboarding screens. Specifically: the one in the screenshot doesn't accept any input.

![IMG_4233](https://user-images.githubusercontent.com/5417572/190303435-0ccf5e58-7cc1-45ee-8668-8d7871b09d09.PNG)

**Comment by mplorentz** [comment]
Hey @quickdudley, thanks for reporting this. I can't reproduce it on any of my own devices. We had a similar issue a few weeks ago, but it was on the screen where you set your bio. It seems to be caused by a bug on Apple's side, which is really frustrating. Could you let me know:
- your device model
- your OS version
- if you have any unusual accessibility settings enabled?

**Comment by quickdudley** [comment]
- Device model: iPhone X
- OS version: iOS 15.6.1
- Default accessibility settings, dark mode

I found that this bug is triggered specifically by the "I'll do it later" button.

**Comment by mplorentz** [comment]
Ah! I happen to have an iPhone X and was able to reproduce this using the "I'll do it later" button. Very weird that it doesn't happen on my iPhone 12 mini or iPad. Taking a closer look today 👀 .

**Comment by mplorentz** [comment]
This bug is the worst.
- It only happens on release builds, not debug builds, so I can't hook up a debugger or use the simulator.
- It doesn't seem to happen on most models of iPhone or any iPads.
- No errors are printed in the logs.

I am starting to think this is a bug on Apple's side and only affects devices running something newer than iOS 15.6 but older than iOS 16.0. But this is difficult to verify. @quickdudley is there any chance you were planning to upgrade to iOS 16 in the near future?

**Comment by mplorentz** [comment]
@quickdudley I finally figured this one out and a fix should be deployed to production on Monday. Thanks for your help!
